apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-postgres-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.postgresqlPassword | b64enc | quote }}
